### PR TITLE
Prep for 1.0.0

### LINKED ISSUE #21: Allow setting raise_on_mismatch per Experiment
It would be really useful for a certain project I'm working on to be able to set the `raise_on_mismatch` setting at the Experiment level, instead of a class level attribute.  Something like:

```
science("my-experiment") do |e|
  e.raise_on_mismatches = true
  e.control {}
  e.candidate {}
end
```

What do you think?

### PR DESCRIPTION
**Pull request by jbarnette**
@jesseplusplus @rick @zerowidth This bumps us to 1.0.0 and tweaks a few of our deps.

fixes #21, fixes #24

### CODE REVIEW

**Comment by jbarnette** [comment]
It's a bad RubyGems/bundler combination on the 1.9.3 build. I'm going to remove the 1.9.3 build for now.

**Comment by jbarnette** [comment]
Feels on removing 1.9.3 from CI? I'm happy to have 1.9 support be best-effort. Since we're not using it I don't want to spend time figuring out a way around the RG/bundler problem.

**Comment by jesseplusplus** [comment]
1.9.x is pretty far behind now, so I'm :+1: to removing it -- especially if it's not being supported well in rubygems/bundler. It would be cool if we had data on how many people are using it with 1.9.3, but alas. If it turns out there are a lot of people still using that, we can always put it back!

**Comment by jesseplusplus** [comment]
also :+1: to these changes

**Comment by zerowidth** [comment]
I'm fine with removing 1.9 CI support, but let's try and keep the syntax compatible (see #7) -- there are some users who are stuck on older rubies still.

**Comment by jesseplusplus** [comment]
Looks like there's a potential fix in #28 for 1.9 on CI.

**Comment by jbarnette** [comment]
Merged in `master` and we're :green_apple:. I'm gonna pull the CI and minitest version bumps into separate PRs so the `1.0.0` bump can be its own thing.

**Pull request closed without merging**
