### PR TITLE
Added Coveralls for code coverage tracking

### PR DESCRIPTION
**Pull request by nickmerwin**
Here's the shiny new badge added to the README:

screen shot 2016-02-05 at 11 13 04 am

And the coverage tracking:

screen shot 2016-02-05 at 11 08 40 am

Currently [here](https://coveralls.io/github/nickmerwin/scientist) but we'll move it to the proper repo url after merging.

Thanks!

### CODE REVIEW

**Comment by natesholland** [comment]
I like the idea! For some reason bundler failed in Ruby 2.1.8 building native extensions.

**Comment by nickmerwin** [comment]
Hey @natesholland I'm finding some evidence that this is an issue with Travis:
https://travis-ci.org/bundler/bundler/jobs/76333985
https://travis-ci.org/rails/web-console/jobs/104453431

I'll keep researching the cause.

**Comment by nickmerwin** [comment]
@natesholland aha! I was able to fix that issue by explicitly including the missing apt package in `.travis.yml`:

```yaml
addons:
 apt:
   packages:
     - libgmp-dev
```

**Comment by strand** [comment]
Is there anything blocking this PR from being merged?

**Comment by jbarnette** [comment]
@strand Thank you for the ping early this year, I'm sorry I missed it!

@nickmerwin Hello from the future, several hundred years after you opened this PR. 🙀 I love calling out coverage in the README. You still :+1: on merging this?

**Comment by nickmerwin** [comment]
@jbarnette hello fellow future traveler! Good to go 👍

**Comment by jbarnette** [comment]
@nickmerwin 🚀 Will you switch coveralls to the proper repo when you have a sec?

**Comment by nickmerwin** [comment]
@jbarnette done! 🎉  

Also, we should make your user the owner of the repo so PR status API calls can be made with your OAuth token -- you'd just need to log into Coveralls and then I can update it. Let me know, thanks!

**Pull request merged**
