### PR TITLE
Add alternatives section to the readme.

### PR DESCRIPTION
**Pull request by daylerees**
Thanks!

### CODE REVIEW

**Comment by jbarnette** [comment]
Thanks @daylerees! I'm going to leave this open for a bit, I might cherry-pick your https://github.com/daylerees/scientist-1/commit/e7cc6934ba83b08851c35a77015070fd6629f560 into a PR with a few tweaks and other alternatives.

**Comment by natesholland** [comment]
:+1:

**Comment by ad-m** [comment]
LGTM

**Comment by Haacked** [comment]
A .NET implementation (in C#) is here: https://github.com/haacked/scientist.net

**Comment by joealcorn** [comment]
I'm working on a Python version as well https://github.com/joealcorn/laboratory

**Comment by jesseplusplus** [comment]
I was also alerted to a Node.js version that @trello has created and used: https://github.com/trello/scientist

**Comment by MadcapJake** [comment]
Just finishing up a few remaining tests and I'll have a complete rewrite in Perl 6: https://github.com/MadcapJake/Test-Lab

**Comment by rawls238** [comment]
I'm starting to work on a Java version here: https://github.com/rawls238/Scientist4J

**Comment by tomiaijo** [comment]
I have a somewhat complete C++ port here: https://github.com/tomiaijo/scientist

**Comment by rawls238** [comment]
any reason not to merge this in + add the additional ports?

**Comment by tcrayford** [comment]
There's a clojure port that's been around a while: https://github.com/yeller/laboratory

**Comment by ziyasal** [comment]
Node/js implementation (in ES6) is here: https://github.com/ziyasal/scientist.js

**Comment by lancew** [comment]
Adding to the list:
Perl 5 : https://github.com/lancew/Scientist
Perl 6 : https://github.com/lancew/ScientistP6 (Smaller less feature complete compared to @MadcapJake 's Test::Lab)

**Comment by jbarnette** [comment]
> any reason not to merge this in + add the additional ports?

@rawls238 Nope! :ship:

**Pull request merged**
