### PR TITLE
1.0.0

### PR DESCRIPTION
**Pull request by jbarnette**
:construction:

To release:

- [ ] :ship:
- [ ] `gd github/scientist && git pull && git checkout master`
- [ ] `script/release`

### CODE REVIEW

**Comment by jbarnette** [comment]
A few open questions:

- [ ] Since the CLA check works on PRs automatically, should we clean up our committed [`CLA.md`](https://github.com/github/scientist/blob/0758fe3fe7e65fce6c4cea01dbc24bcf9a9998d6/CLA.md) and [`CONTRIBUTING.md`](https://github.com/github/scientist/blob/0758fe3fe7e65fce6c4cea01dbc24bcf9a9998d6/CONTRIBUTING.md)? Right now they're a little out of sync w/the current process.

- [ ] Should we fix the gemspec [authors and emails](https://github.com/github/scientist/blob/master/scientist.gemspec#L7-L8)? Right now it's just me and @rick. If we want to fix it, should we list everyone w/public emails or make a new `@github.com` forwarding list?

/cc @github/open-source

**Comment by jbarnette** [comment]
I've added GitHub Open Source as an author so there's at least a shared address. @jesseplusplus @rick @zerowidth Do y'all want to be listed in the gemspec? Just web edit in this PR if you do. I can also remove all of us and just leave the alias if nobody wants the hassle.

**Comment by zerowidth** [comment]
@github/open-source if this project is governed by the CLA using the build hook / CLA tool, do we need to include the text of the CLA within the project itself?

**Comment by mlinksva** [comment]
@zerowidth no, none of the other projects using the CLA includes the text in within the project.

**Comment by jbarnette** [comment]
Anybody got candidates for a short and sweet replacement `CONTRIBUTING.md`? Our contributions are super low volume but it'd still be good to have something.

**Comment by jbarnette** [comment]
Should we do a prerelease, even if it's just for ourselves? Not a ton of change but there's some stuff: https://github.com/github/scientist/compare/v0.0.4...one-dot-oh-dot-oh

**Comment by jbarnette** [comment]
Found a template, I'll add it. :bow: @mlinksva

**Comment by jbarnette** [comment]
:confetti_ball:

**Comment by jbarnette** [comment]
Related post by @jesseplusplus: http://githubengineering.com/scientist

**Comment by rick** [comment]
:white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::busstop::star::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square:
:white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::fork_and_knife::star::star::white_large_square::white_large_square::white_large_square::white_large_square:
:white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::fork_and_knife::100::100::white_large_square::white_large_square::white_large_square::white_large_square:
:white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::fork_and_knife::star::star::white_large_square::white_large_square::white_large_square::white_large_square:
:white_large_square::white_large_square::white_large_square::white_large_square::100::fork_and_knife::star::star::star::white_large_square::white_large_square::white_large_square:
:white_large_square::white_large_square::white_large_square::white_large_square::star::fork_and_knife::boom::boom::boom::white_large_square::white_large_square::white_large_square:
:white_large_square::white_large_square::white_large_square::star::star::fork_and_knife::boom::boom::boom::boom::white_large_square::white_large_square:
:white_large_square::white_large_square::boom::boom::boom::fork_and_knife::100::100::100::100::white_large_square::white_large_square:
:white_large_square::white_large_square::100::100::100::fork_and_knife::100::100::100::100::100::white_large_square:
:white_large_square::100::100::100::100::fork_and_knife::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square::white_large_square:
:white_large_square::crown::crown::crown::crown::fork_and_knife::crown::crown::crown::crown::crown::white_large_square:
:white_large_square::white_large_square::construction::crown::crown::crown::crown::crown::crown::crown::construction::white_large_square:

**Comment by jesseplusplus** [comment]
:smile_cat:  @rick your mega-emoji game is always on point!

**Comment by rick** [comment]
:bow: 

Wishing you guys the best! Hope everything is well.

**Comment by arthurnn** [comment]
🎉

**Pull request merged**
